FROM php:8.3.0RC6-fpm

# Set working directory
WORKDIR /var/www/

# Install dependencies
RUN apt-get update -y && \
    apt-get install -yq \
    autoconf \
    curl \
    supervisor \
    wget \
    libfreetype6-dev \
    libzip-dev \
    zip \
    cron

RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli

# Install extensions
RUN docker-php-ext-install exif pcntl sockets zip

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Expose port 9000 and start php-fpm server
EXPOSE 9000

RUN echo "*/1 * * * * php /var/www/artisan schedule:run >> /var/log/cron.log 2>&1" >> /etc/crontab


# Create the log file to be able to run tail
RUN touch /var/log/cron.log

COPY ./app/ .

RUN chmod -R 777 /var/www/storage

CMD ["supervisord", "-c", "/etc/supervisor/supervisord.conf"]
