FROM php:8.0.5-fpm

# Set working directory
WORKDIR /var/www/

# Install dependencies
RUN apt-get update -y && \
    apt-get install -yq \
    autoconf \
    curl \
    supervisor \
    wget \
    git \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libonig-dev \
    libzip-dev \
    zip \
    ffmpeg \
    openssl \
    sshpass \
    nginx \
    cron

# Install GD extension
RUN docker-php-ext-configure gd --with-freetype --with-jpeg
RUN docker-php-ext-install -j "$(nproc)" gd
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli

# Install extensions
RUN docker-php-ext-install exif pcntl sockets zip

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Swoole extension
#RUN pecl install swoole
#RUN docker-php-ext-enable swoole

# Change current user to root
USER root

# Expose port 9000 and start php-fpm server
EXPOSE 9000

RUN echo "*/1 * * * * php /var/www/artisan schedule:run >> /var/log/cron.log 2>&1" >> /etc/crontab


# Create the log file to be able to run tail
RUN touch /var/log/cron.log

CMD ["/var/www/docker/php/run.sh"]
