version: "3.9"
services:
    php:
        container_name: task-app
        privileged: true
        build:
            context: .
            dockerfile: docker/php/dockerfile
        volumes:
            - ./app/:/var/www/:rwx
            - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/php/supervisor:/etc/supervisor
            - ./docker/php/cron.d:/etc/cron.d
        depends_on:
            - redis
        networks:
            - task
    nginx:
        container_name: task-nginx
        build:
            context: .
            dockerfile: docker/nginx/dockerfile
        ports:
            - "8000:80"
        depends_on:
            - php
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./app/:/var/www/
        networks:
            - task
    redis:
        build:
            context: docker/redis
            dockerfile: dockerfile
        container_name: task-redis
        volumes:
          - ./redis-data:/opt/redis/data
        ports:
            - "6388:6379"
        networks:
            - task
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: "swagger-ui"
        ports:
            - "8071:8080"
        volumes:
            - ./swagger.json:/openapi.json
        environment:
            SWAGGER_JSON: /openapi.json
        networks:
            - task

networks:
    task:
        driver: bridge
